using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Leaderboard panel theo phong cách game mobile (Helix Jump-like):
/// header LEADERBOARD vàng, tab Daily/Weekly/AllTime, header row RANK/NAME/SCORE,
/// scroll list player với medal Top 3, footer YOU.
/// Thêm dataset fake để demo khi chưa nối Firebase.
/// </summary>
[RequireComponent(typeof(RectTransform))]
public class LeaderboardPanel : MonoBehaviour
{
    public enum LeaderboardTab
    {
        Daily,
        Weekly,
        AllTime,
    }

    [Header("Liên kết tuỳ chọn")]
    [Tooltip("Nếu để trống: lấy từ LeagueManager đầu tiên trong scene.")]
    public LeagueManager leagueManagerOverride;
    [Tooltip("UIManager để nút Back biết quay về Map. Nếu trống sẽ tự tìm.")]
    public UIManager uiManagerOverride;

    [Header("Tuỳ chỉnh hiển thị")]
    public string title = "LEADERBOARD";
    public string localPlayerFallbackName = "You";
    [Tooltip("Số dòng hiển thị tối đa.")]
    public int maxRows = 30;
    [Tooltip("Chiều cao mỗi dòng player.")]
    public float rowHeight = 110f;
    [Tooltip("Khoảng cách giữa các dòng.")]
    public float rowSpacing = 4f;

    [Header("Nguồn dữ liệu")]
    [Tooltip("Bật để đọc leaderboard từ Firebase Realtime Database. Tự fallback về demo nếu service chưa cấu hình.")]
    public bool useFirebase = true;
    [Tooltip("Tham chiếu service. Để trống sẽ tự tìm trong scene.")]
    public FirebaseLeaderboardService firebaseServiceOverride;
    [Tooltip("Khi đang fetch Firebase: hiện thông báo loading.")]
    public string loadingMessage = "Loading leaderboard...";
    [Tooltip("Khi fetch Firebase lỗi: hiện thông báo này.")]
    public string errorMessage = "Could not connect to Firebase.";

    [Header("Demo player (khi chưa nối Firebase)")]
    [Tooltip("Tự sinh player demo nếu list từ LeagueManager nhỏ hơn ngưỡng.")]
    public bool autoGenerateDemoPlayers = true;
    [Tooltip("Số demo player mục tiêu khi sinh tự động.")]
    public int demoPlayerTargetCount = 30;
    [Tooltip("Seed để demo data luôn ổn định giữa các lần mở.")]
    public int demoSeed = 12345;

    [Header("Bảng màu")]
    public Color backgroundTop = new Color(0.20f, 0.46f, 1f, 1f);
    public Color backgroundBottom = new Color(0.05f, 0.13f, 0.45f, 1f);
    public Color titleColor = new Color(1f, 0.84f, 0.20f, 1f);
    public Color headerStripColor = new Color(0.04f, 0.10f, 0.34f, 0.92f);
    public Color tabActiveColor = new Color(1f, 0.84f, 0.20f, 1f);
    public Color tabInactiveColor = new Color(0.85f, 0.92f, 1f, 0.8f);
    public Color rowColorOdd = new Color(0.16f, 0.34f, 0.86f, 0.92f);
    public Color rowColorEven = new Color(0.11f, 0.26f, 0.74f, 0.92f);
    public Color rowYouColor = new Color(0.22f, 0.62f, 0.36f, 0.95f);
    public Color medalGold = new Color(1f, 0.82f, 0.27f, 1f);
    public Color medalSilver = new Color(0.85f, 0.90f, 1f, 1f);
    public Color medalBronze = new Color(0.96f, 0.66f, 0.40f, 1f);
    public Color scoreColor = new Color(1f, 0.91f, 0.55f, 1f);
    public Color youHighlight = new Color(0.66f, 1f, 0.74f, 1f);

    LeagueManager leagueManager;
    UIManager uiManager;
    FirebaseLeaderboardService firebaseService;
    RectTransform rowsContainer;
    ScrollRect scrollRect;
    TextMeshProUGUI titleText;
    TextMeshProUGUI youRankText;
    TextMeshProUGUI youNameText;
    TextMeshProUGUI youScoreText;
    TextMeshProUGUI statusText;
    TextMeshProUGUI countdownText;
    TextMeshProUGUI tierBadgeText;
    Image tierBadgeBg;
    Image youFooterBackground;
    readonly List<LeaderboardRowView> rowViews = new List<LeaderboardRowView>();
    readonly List<TabButton> tabButtons = new List<TabButton>();
    readonly Dictionary<LeaderboardTab, List<LeaguePlayerData>> demoCache = new Dictionary<LeaderboardTab, List<LeaguePlayerData>>();

    LeaderboardTab activeTab = LeaderboardTab.AllTime;
    bool isBuilt;
    bool isFetching;
    Sprite circleSprite;
    Sprite roundedSprite;
    Sprite backgroundSprite;
    // Tracking để cleanup texture/sprite tránh leak khi scene reload nhiều lần.
    readonly List<Object> generatedAssets = new List<Object>();

    class LeaderboardRowView
    {
        public GameObject root;
        public Image background;
        public Image medalBadge;
        public TextMeshProUGUI rankText;
        public TextMeshProUGUI nameText;
        public TextMeshProUGUI scoreText;
    }

    class TabButton
    {
        public LeaderboardTab tab;
        public TextMeshProUGUI label;
        public RectTransform underline;
    }

    void Awake()
    {
        EnsureBuilt();
    }

    void OnEnable()
    {
        EnsureBuilt();
        ForceFullScreenAndOnTop();
        // Tin tưởng UIManager xử lý việc ẩn các panel cũ (MapPanel/SkinsPanel/LeaguePanel).
        // KHÔNG gọi HideConflictingPanels nữa vì nó làm các children của MapPanel
        // (PlayButton, ADs, Setting gear) không khôi phục đúng sau khi Back.
        firebaseCacheRaw = null;
        // Nếu panel bị đóng giữa lúc đang fetch, isFetching có thể kẹt true
        // → reset để OnEnable kế tiếp luôn fetch lại được.
        isFetching = false;
        StartCoroutine(RefreshNextFrame());
    }

    void ForceFullScreenAndOnTop()
    {
        RectTransform self = (RectTransform)transform;
        self.anchorMin = Vector2.zero;
        self.anchorMax = Vector2.one;
        self.pivot = new Vector2(0.5f, 0.5f);
        self.offsetMin = Vector2.zero;
        self.offsetMax = Vector2.zero;
        self.localScale = Vector3.one;
        self.localRotation = Quaternion.identity;
        transform.SetAsLastSibling();
    }

    IEnumerator RefreshNextFrame()
    {
        yield return null;
        Refresh();
        if (scrollRect != null)
        {
            scrollRect.verticalNormalizedPosition = 1f;
        }
    }

    public void Refresh()
    {
        if (!isBuilt)
        {
            EnsureBuilt();
        }

        leagueManager = leagueManagerOverride != null ? leagueManagerOverride : FindLeagueManager();
        uiManager = uiManagerOverride != null ? uiManagerOverride : FindUIManager();
        firebaseService = firebaseServiceOverride != null ? firebaseServiceOverride : FindFirebaseService();

        UpdateTabVisuals();

        if (useFirebase && firebaseService != null && firebaseService.IsConfigured)
        {
            if (firebaseCacheRaw != null)
            {
                RenderRanking(BuildRankingFromFirebaseCache());
            }
            else
            {
                ShowStatus(loadingMessage);
                if (!isFetching)
                {
                    StartCoroutine(FetchFromFirebaseRoutine());
                }
            }
        }
        else
        {
            HideStatus();
            RenderRanking(BuildRankingForTab(activeTab));
        }
    }

    IEnumerator FetchFromFirebaseRoutine()
    {
        isFetching = true;
        bool finished = false;
        List<FirebasePlayerEntry> result = null;

        firebaseService.FetchAll(entries =>
        {
            result = entries;
            finished = true;
        });

        float waited = 0f;
        while (!finished && waited < 12f)
        {
            waited += Time.unscaledDeltaTime;
            yield return null;
        }

        isFetching = false;

        if (result == null)
        {
            ShowStatus(errorMessage);
            yield break;
        }

        // Chỉ giữ entry thuộc mùa hiện tại (auto weekly filter).
        string currentSeason = SeasonManager.GetCurrentSeasonId();
        List<FirebasePlayerEntry> filtered = new List<FirebasePlayerEntry>();
        for (int i = 0; i < result.Count; i++)
        {
            FirebasePlayerEntry e = result[i];
            if (e == null) continue;
            // Entry không có season được coi như "mùa hiện tại" để không loại nhầm seed cũ.
            if (string.IsNullOrEmpty(e.season) || e.season == currentSeason)
            {
                filtered.Add(e);
            }
        }

        ConvertFirebaseEntries(filtered);
        HideStatus();
        RenderRanking(BuildRankingFromFirebaseCache());
    }

    public void ForceReloadFromFirebase()
    {
        firebaseCacheRaw = null;
        Refresh();
    }

    // Cache giữ id/updatedAt để filter Daily/Weekly và xác định local player chính xác
    class CachedEntry
    {
        public string id;
        public string playerName;
        public int score;
        public long updatedAt;
    }
    List<CachedEntry> firebaseCacheRaw;

    void ConvertFirebaseEntries(List<FirebasePlayerEntry> entries)
    {
        firebaseCacheRaw = new List<CachedEntry>();
        if (entries == null) return;

        for (int i = 0; i < entries.Count; i++)
        {
            FirebasePlayerEntry e = entries[i];
            if (e == null || string.IsNullOrWhiteSpace(e.name)) continue;
            firebaseCacheRaw.Add(new CachedEntry
            {
                id = e.id,
                playerName = e.name.Trim(),
                score = Mathf.Max(0, e.score),
                updatedAt = e.updatedAt
            });
        }
    }

    List<LeaguePlayerData> BuildRankingFromFirebaseCache()
    {
        long nowUnix = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        long cutoff = activeTab == LeaderboardTab.Daily ? nowUnix - 86400L
                    : activeTab == LeaderboardTab.Weekly ? nowUnix - 86400L * 7L
                    : 0L;

        List<LeaguePlayerData> snapshot = new List<LeaguePlayerData>();
        if (firebaseCacheRaw == null) return snapshot;

        for (int i = 0; i < firebaseCacheRaw.Count; i++)
        {
            CachedEntry e = firebaseCacheRaw[i];
            // Daily/Weekly: chỉ giữ entry có updatedAt mới đủ. AllTime: lấy hết.
            // Entry có updatedAt = 0 (seed cũ chưa có timestamp) coi như AllTime.
            if (cutoff > 0 && e.updatedAt > 0 && e.updatedAt < cutoff) continue;
            snapshot.Add(new LeaguePlayerData
            {
                playerName = e.playerName,
                score = e.score
            });
        }
        snapshot.Sort(SortByScore);
        return snapshot;
    }

    void RenderRanking(List<LeaguePlayerData> ranking)
    {
        string localPlayerName = ResolveLocalPlayerName();

        int rowCount = Mathf.Clamp(maxRows, 1, 200);
        rowCount = Mathf.Min(rowCount, ranking.Count);
        EnsureRowViews(rowCount);

        for (int i = 0; i < rowViews.Count; i++)
        {
            LeaderboardRowView row = rowViews[i];
            bool active = i < rowCount;
            row.root.SetActive(active);
            if (!active)
            {
                continue;
            }

            int rank = i + 1;
            LeaguePlayerData player = ranking[i];
            bool isYou = string.Equals(player.playerName, localPlayerName, System.StringComparison.OrdinalIgnoreCase);

            row.background.color = isYou ? rowYouColor : (i % 2 == 0 ? rowColorOdd : rowColorEven);

            if (rank <= 3)
            {
                row.medalBadge.gameObject.SetActive(true);
                row.medalBadge.color = MedalColor(rank);
                row.rankText.text = string.Empty;
            }
            else
            {
                row.medalBadge.gameObject.SetActive(false);
                row.rankText.text = rank.ToString();
            }

            row.nameText.text = isYou ? "<b>" + TrimName(player.playerName) + "</b>" : TrimName(player.playerName);
            row.nameText.color = isYou ? youHighlight : Color.white;

            row.scoreText.text = FormatScore(player.score);
        }

        UpdateYouFooter(ranking, localPlayerName);
        UpdateTierBadge(ranking, localPlayerName);
    }

    void UpdateTierBadge(List<LeaguePlayerData> ranking, string localPlayerName)
    {
        if (tierBadgeText == null || tierBadgeBg == null) return;

        int localScore = 0;
        // Ưu tiên dùng ID Firebase (khớp 100%, không bị nhầm tên trùng) → chuẩn hơn
        // việc so sánh playerName. Fallback sang so theo tên nếu không có cache Firebase.
        if (firebaseCacheRaw != null && firebaseService != null && !string.IsNullOrEmpty(firebaseService.LocalPlayerId))
        {
            string myId = firebaseService.LocalPlayerId;
            for (int i = 0; i < firebaseCacheRaw.Count; i++)
            {
                if (firebaseCacheRaw[i].id == myId)
                {
                    localScore = firebaseCacheRaw[i].score;
                    break;
                }
            }
        }
        else
        {
            for (int i = 0; i < ranking.Count; i++)
            {
                if (string.Equals(ranking[i].playerName, localPlayerName, System.StringComparison.OrdinalIgnoreCase))
                {
                    localScore = ranking[i].score;
                    break;
                }
            }
        }

        LeagueTier tier = LeagueTierSystem.GetTierForScore(localScore);
        tierBadgeText.text = tier.displayName.ToUpperInvariant();
        tierBadgeBg.color = new Color(tier.primaryColor.r, tier.primaryColor.g, tier.primaryColor.b, 0.85f);
        tierBadgeText.color = Color.white;
    }

    float _nextCountdownUpdate;
    void Update()
    {
        if (countdownText == null || !gameObject.activeInHierarchy) return;
        if (Time.unscaledTime < _nextCountdownUpdate) return;
        _nextCountdownUpdate = Time.unscaledTime + 1f;
        countdownText.text = "Season ends in " + SeasonManager.FormatCountdown(SeasonManager.GetTimeUntilSeasonEnd());
    }

    string ResolveLocalPlayerName()
    {
        if (firebaseService != null && !string.IsNullOrWhiteSpace(firebaseService.LocalPlayerName))
        {
            return firebaseService.LocalPlayerName;
        }
        return PlayerPrefs.GetString("PlayerName", localPlayerFallbackName);
    }

    void UpdateYouFooter(List<LeaguePlayerData> ranking, string localPlayerName)
    {
        int localRank = -1;
        int localScore = 0;
        for (int i = 0; i < ranking.Count; i++)
        {
            if (string.Equals(ranking[i].playerName, localPlayerName, System.StringComparison.OrdinalIgnoreCase))
            {
                localRank = i + 1;
                localScore = ranking[i].score;
                break;
            }
        }

        youFooterBackground.color = new Color(0.05f, 0.10f, 0.36f, 0.96f);
        youRankText.text = localRank > 0 ? localRank.ToString() : "-";
        youNameText.text = "<b>" + TrimName(localPlayerName) + "</b>";
        youScoreText.text = localRank > 0 ? FormatScore(localScore) : "-";
    }

    List<LeaguePlayerData> BuildRankingForTab(LeaderboardTab tab)
    {
        List<LeaguePlayerData> result;
        if (!demoCache.TryGetValue(tab, out result))
        {
            result = BuildBaseRanking(tab);
            demoCache[tab] = result;
        }
        else
        {
            UpdateLocalPlayerInList(result);
        }
        result.Sort(SortByScore);
        return result;
    }

    void UpdateLocalPlayerInList(List<LeaguePlayerData> list)
    {
        // Chỉ chạy ở fallback demo (khi Firebase OFF). Ở chế độ Firebase, entry của
        // local player được fetch trực tiếp trong list nên không cần inject thủ công.
        string localName = ResolveLocalPlayerName();
        int localScore = 0;

        for (int i = 0; i < list.Count; i++)
        {
            if (string.Equals(list[i].playerName, localName, System.StringComparison.OrdinalIgnoreCase))
            {
                return;
            }
        }
        list.Add(new LeaguePlayerData { playerName = localName, score = localScore });
    }

    List<LeaguePlayerData> BuildBaseRanking(LeaderboardTab tab)
    {
        List<LeaguePlayerData> result = new List<LeaguePlayerData>();

        if (leagueManager != null && leagueManager.localTestPlayers != null)
        {
            for (int i = 0; i < leagueManager.localTestPlayers.Length; i++)
            {
                LeaguePlayerData src = leagueManager.localTestPlayers[i];
                if (src == null || string.IsNullOrWhiteSpace(src.playerName))
                {
                    continue;
                }
                result.Add(new LeaguePlayerData
                {
                    playerName = src.playerName.Trim(),
                    score = Mathf.Max(0, src.score)
                });
            }
        }

        if (autoGenerateDemoPlayers && result.Count < demoPlayerTargetCount)
        {
            int needed = demoPlayerTargetCount - result.Count;
            int multiplier = TabScoreMultiplier(tab);
            int seed = unchecked(demoSeed + (int)tab * 7919);
            System.Random rng = new System.Random(seed);
            for (int i = 0; i < needed; i++)
            {
                string fakeName = GenerateFakeName(rng);
                int baseScore = rng.Next(150, 9000);
                result.Add(new LeaguePlayerData
                {
                    playerName = fakeName,
                    score = baseScore * multiplier
                });
            }
        }

        UpdateLocalPlayerInList(result);
        return result;
    }

    static int TabScoreMultiplier(LeaderboardTab tab)
    {
        switch (tab)
        {
            case LeaderboardTab.Daily: return 1;
            case LeaderboardTab.Weekly: return 4;
            default: return 12;
        }
    }

    static int SortByScore(LeaguePlayerData a, LeaguePlayerData b)
    {
        int byScore = b.score.CompareTo(a.score);
        if (byScore != 0)
        {
            return byScore;
        }
        return string.Compare(a.playerName, b.playerName, System.StringComparison.OrdinalIgnoreCase);
    }

    string GenerateFakeName(System.Random rng)
    {
        string[] prefixes = { "Player", "Helix", "Bouncy", "Drop", "Spin", "Jump", "Crash", "Neon", "Pixel", "Comet" };
        string prefix = prefixes[rng.Next(prefixes.Length)];
        int number = rng.Next(10, 999);
        return prefix + number;
    }

    LeagueManager FindLeagueManager()
    {
        LeagueManager[] managers = Object.FindObjectsByType<LeagueManager>(FindObjectsInactive.Include, FindObjectsSortMode.None);
        return managers != null && managers.Length > 0 ? managers[0] : null;
    }

    UIManager FindUIManager()
    {
        UIManager[] managers = Object.FindObjectsByType<UIManager>(FindObjectsInactive.Include, FindObjectsSortMode.None);
        return managers != null && managers.Length > 0 ? managers[0] : null;
    }

    FirebaseLeaderboardService FindFirebaseService()
    {
        if (FirebaseLeaderboardService.instance != null)
        {
            return FirebaseLeaderboardService.instance;
        }
        FirebaseLeaderboardService[] all = Object.FindObjectsByType<FirebaseLeaderboardService>(FindObjectsInactive.Include, FindObjectsSortMode.None);
        return all != null && all.Length > 0 ? all[0] : null;
    }

    void ShowStatus(string message)
    {
        if (statusText == null) return;
        statusText.gameObject.SetActive(true);
        statusText.text = message;
    }

    void HideStatus()
    {
        if (statusText == null) return;
        statusText.gameObject.SetActive(false);
    }

    void EnsureRowViews(int needed)
    {
        while (rowViews.Count < needed)
        {
            rowViews.Add(CreateRow(rowViews.Count));
        }
    }

    void EnsureBuilt()
    {
        if (isBuilt)
        {
            return;
        }
        BuildPanel();
        isBuilt = true;
    }

    void BuildPanel()
    {
        ClearChildren(transform);

        RectTransform self = (RectTransform)transform;
        self.anchorMin = Vector2.zero;
        self.anchorMax = Vector2.one;
        self.offsetMin = Vector2.zero;
        self.offsetMax = Vector2.zero;

        circleSprite = BuildCircleSprite(128);
        roundedSprite = BuildRoundedSprite(64, 16);
        if (circleSprite != null)
        {
            generatedAssets.Add(circleSprite);
            if (circleSprite.texture != null) generatedAssets.Add(circleSprite.texture);
        }
        if (roundedSprite != null)
        {
            generatedAssets.Add(roundedSprite);
            if (roundedSprite.texture != null) generatedAssets.Add(roundedSprite.texture);
        }

        AddBackgroundGradient(self);
        BuildHeaderArea(self);
        BuildTabsArea(self);
        BuildHeaderRow(self);
        BuildScrollList(self);
        BuildYouFooter(self);
    }

    void AddBackgroundGradient(RectTransform parent)
    {
        GameObject bg = new GameObject("Background", typeof(RectTransform), typeof(Image));
        bg.transform.SetParent(parent, false);
        StretchFull((RectTransform)bg.transform);

        Image img = bg.GetComponent<Image>();
        Texture2D tex = BuildGradientTexture(2, 256, backgroundTop, backgroundBottom);
        backgroundSprite = Sprite.Create(tex, new Rect(0f, 0f, tex.width, tex.height), new Vector2(0.5f, 0.5f));
        generatedAssets.Add(tex);
        generatedAssets.Add(backgroundSprite);
        img.sprite = backgroundSprite;
        img.type = Image.Type.Simple;
        img.preserveAspect = false;
        img.raycastTarget = true;
    }

    void OnDestroy()
    {
        for (int i = 0; i < generatedAssets.Count; i++)
        {
            Object asset = generatedAssets[i];
            if (asset != null) Destroy(asset);
        }
        generatedAssets.Clear();
    }

    void BuildHeaderArea(RectTransform parent)
    {
        RectTransform header = CreateChildRect(parent, "Header",
            new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0.5f, 1f),
            new Vector2(0f, -150f), new Vector2(0f, 0f));

        TextMeshProUGUI label = CreateText(header, "TitleText", title, 80f, FontStyles.Bold, TextAlignmentOptions.Center);
        label.color = titleColor;
        StretchFull((RectTransform)label.transform);
        titleText = label;

        // Đồng hồ đếm ngược ngay dưới tiêu đề
        RectTransform timerRow = CreateChildRect(parent, "CountdownRow",
            new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0.5f, 1f),
            new Vector2(0f, -200f), new Vector2(0f, -150f));
        TextMeshProUGUI timer = CreateText(timerRow, "CountdownText", "Season ends in --", 32f, FontStyles.Italic, TextAlignmentOptions.Center);
        timer.color = new Color(0.85f, 0.95f, 1f, 0.85f);
        StretchFull((RectTransform)timer.transform);
        countdownText = timer;

        BuildBackButton(parent);
        BuildTierBadge(parent);
    }

    void BuildTierBadge(RectTransform parent)
    {
        GameObject badgeGo = new GameObject("TierBadge", typeof(RectTransform), typeof(Image), typeof(HorizontalLayoutGroup));
        badgeGo.transform.SetParent(parent, false);
        RectTransform rect = (RectTransform)badgeGo.transform;
        rect.anchorMin = new Vector2(1f, 1f);
        rect.anchorMax = new Vector2(1f, 1f);
        rect.pivot = new Vector2(1f, 1f);
        rect.anchoredPosition = new Vector2(-30f, -55f);
        rect.sizeDelta = new Vector2(260f, 90f);

        Image img = badgeGo.GetComponent<Image>();
        img.sprite = roundedSprite;
        img.type = Image.Type.Sliced;
        img.color = new Color(1f, 1f, 1f, 0.22f);
        tierBadgeBg = img;

        HorizontalLayoutGroup horizontal = badgeGo.GetComponent<HorizontalLayoutGroup>();
        horizontal.padding = new RectOffset(20, 20, 8, 8);
        horizontal.spacing = 12f;
        horizontal.childAlignment = TextAnchor.MiddleCenter;
        horizontal.childControlHeight = true;
        horizontal.childControlWidth = true;
        horizontal.childForceExpandHeight = true;
        horizontal.childForceExpandWidth = true;

        TextMeshProUGUI label = CreateText(badgeGo.transform, "TierLabel", "BRONZE", 38f, FontStyles.Bold, TextAlignmentOptions.Center);
        label.color = Color.white;
        label.raycastTarget = false;
        tierBadgeText = label;
    }

    void BuildBackButton(RectTransform parent)
    {
        GameObject btnGo = new GameObject("BackButton", typeof(RectTransform), typeof(Image), typeof(Button));
        btnGo.transform.SetParent(parent, false);
        RectTransform rect = (RectTransform)btnGo.transform;
        rect.anchorMin = new Vector2(0f, 1f);
        rect.anchorMax = new Vector2(0f, 1f);
        rect.pivot = new Vector2(0f, 1f);
        rect.anchoredPosition = new Vector2(40f, -50f);
        rect.sizeDelta = new Vector2(110f, 110f);

        Image img = btnGo.GetComponent<Image>();
        img.sprite = roundedSprite;
        img.color = new Color(1f, 1f, 1f, 0.18f);
        img.type = Image.Type.Sliced;

        TextMeshProUGUI arrow = CreateText(btnGo.transform, "ArrowText", "<", 80f, FontStyles.Bold, TextAlignmentOptions.Center);
        arrow.color = Color.white;
        StretchFull((RectTransform)arrow.transform);

        Button btn = btnGo.GetComponent<Button>();
        btn.onClick.AddListener(OnBackClicked);
    }

    void OnBackClicked()
    {
        if (uiManager == null)
        {
            uiManager = FindUIManager();
        }
        if (uiManager != null)
        {
            uiManager.OpenMapPanel();
        }
        else
        {
            gameObject.SetActive(false);
        }
    }

    void BuildTabsArea(RectTransform parent)
    {
        RectTransform tabRow = CreateChildRect(parent, "Tabs",
            new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0.5f, 1f),
            new Vector2(40f, -260f), new Vector2(-40f, -200f));

        HorizontalLayoutGroup horizontal = tabRow.gameObject.AddComponent<HorizontalLayoutGroup>();
        horizontal.spacing = 30f;
        horizontal.padding = new RectOffset(0, 0, 0, 0);
        horizontal.childAlignment = TextAnchor.MiddleCenter;
        horizontal.childControlHeight = true;
        horizontal.childControlWidth = true;
        horizontal.childForceExpandHeight = true;
        horizontal.childForceExpandWidth = true;

        tabButtons.Clear();
        AddTab(tabRow, LeaderboardTab.Daily, "Daily");
        AddTab(tabRow, LeaderboardTab.Weekly, "Weekly");
        AddTab(tabRow, LeaderboardTab.AllTime, "All Time");
    }

    void AddTab(Transform parent, LeaderboardTab tab, string label)
    {
        GameObject tabGo = new GameObject("Tab_" + tab, typeof(RectTransform), typeof(Image), typeof(Button), typeof(LayoutElement));
        tabGo.transform.SetParent(parent, false);
        Image img = tabGo.GetComponent<Image>();
        img.color = new Color(0f, 0f, 0f, 0f);

        TextMeshProUGUI labelText = CreateText(tabGo.transform, "Label", label, 44f, FontStyles.Bold, TextAlignmentOptions.Center);
        StretchFull((RectTransform)labelText.transform);

        GameObject lineGo = new GameObject("Underline", typeof(RectTransform), typeof(Image));
        lineGo.transform.SetParent(tabGo.transform, false);
        RectTransform lineRect = (RectTransform)lineGo.transform;
        lineRect.anchorMin = new Vector2(0.5f, 0f);
        lineRect.anchorMax = new Vector2(0.5f, 0f);
        lineRect.pivot = new Vector2(0.5f, 0f);
        lineRect.sizeDelta = new Vector2(140f, 8f);
        lineRect.anchoredPosition = new Vector2(0f, 4f);
        Image lineImg = lineGo.GetComponent<Image>();
        lineImg.color = tabActiveColor;
        lineImg.sprite = roundedSprite;
        lineImg.type = Image.Type.Sliced;

        Button btn = tabGo.GetComponent<Button>();
        LeaderboardTab capturedTab = tab;
        btn.onClick.AddListener(() => SelectTab(capturedTab));

        tabButtons.Add(new TabButton
        {
            tab = tab,
            label = labelText,
            underline = lineRect,
        });
    }

    void SelectTab(LeaderboardTab tab)
    {
        if (activeTab == tab)
        {
            return;
        }
        activeTab = tab;
        if (scrollRect != null)
        {
            scrollRect.verticalNormalizedPosition = 1f;
        }
        Refresh();
    }

    void UpdateTabVisuals()
    {
        for (int i = 0; i < tabButtons.Count; i++)
        {
            TabButton tab = tabButtons[i];
            bool isActive = tab.tab == activeTab;
            tab.label.color = isActive ? tabActiveColor : tabInactiveColor;
            tab.underline.gameObject.SetActive(isActive);
        }
    }

    void BuildHeaderRow(RectTransform parent)
    {
        RectTransform headerRow = CreateChildRect(parent, "HeaderRow",
            new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0.5f, 1f),
            new Vector2(40f, -360f), new Vector2(-40f, -280f));

        Image bg = headerRow.gameObject.AddComponent<Image>();
        bg.color = headerStripColor;
        bg.sprite = roundedSprite;
        bg.type = Image.Type.Sliced;

        HorizontalLayoutGroup row = headerRow.gameObject.AddComponent<HorizontalLayoutGroup>();
        row.padding = new RectOffset(40, 40, 8, 8);
        row.spacing = 18f;
        row.childAlignment = TextAnchor.MiddleCenter;
        row.childControlHeight = true;
        row.childControlWidth = true;
        row.childForceExpandHeight = true;
        row.childForceExpandWidth = false;

        AddHeaderCell(headerRow, "RANK", TextAlignmentOptions.Center, 1f);
        AddHeaderCell(headerRow, "NAME", TextAlignmentOptions.Left, 3f);
        AddHeaderCell(headerRow, "SCORE", TextAlignmentOptions.Right, 1.4f);
    }

    void AddHeaderCell(Transform parent, string text, TextAlignmentOptions align, float weight)
    {
        GameObject cell = new GameObject(text + "Header", typeof(RectTransform), typeof(LayoutElement));
        cell.transform.SetParent(parent, false);
        cell.GetComponent<LayoutElement>().flexibleWidth = weight;

        TextMeshProUGUI label = CreateText(cell.transform, text + "Label", text, 38f, FontStyles.Bold, align);
        label.color = new Color(0.92f, 0.96f, 1f, 1f);
        StretchFull((RectTransform)label.transform);
    }

    void BuildScrollList(RectTransform parent)
    {
        RectTransform listArea = CreateChildRect(parent, "ListArea",
            new Vector2(0f, 0f), new Vector2(1f, 1f), new Vector2(0.5f, 0.5f),
            new Vector2(40f, 230f), new Vector2(-40f, -370f));

        GameObject scrollGo = new GameObject("ScrollView", typeof(RectTransform), typeof(Image), typeof(ScrollRect));
        scrollGo.transform.SetParent(listArea, false);
        StretchFull((RectTransform)scrollGo.transform);

        Image scrollBg = scrollGo.GetComponent<Image>();
        scrollBg.color = new Color(0.04f, 0.10f, 0.32f, 0.45f);
        scrollBg.sprite = roundedSprite;
        scrollBg.type = Image.Type.Sliced;
        scrollBg.raycastTarget = true;

        scrollRect = scrollGo.GetComponent<ScrollRect>();
        scrollRect.horizontal = false;
        scrollRect.vertical = true;
        scrollRect.movementType = ScrollRect.MovementType.Elastic;
        scrollRect.elasticity = 0.12f;
        scrollRect.inertia = true;
        scrollRect.decelerationRate = 0.08f;
        scrollRect.scrollSensitivity = 35f;

        GameObject viewport = new GameObject("Viewport", typeof(RectTransform), typeof(Image), typeof(RectMask2D));
        viewport.transform.SetParent(scrollGo.transform, false);
        StretchFull((RectTransform)viewport.transform);
        Image viewportImg = viewport.GetComponent<Image>();
        viewportImg.color = new Color(0f, 0f, 0f, 0f);
        viewportImg.raycastTarget = true;
        scrollRect.viewport = (RectTransform)viewport.transform;

        GameObject content = new GameObject("Content", typeof(RectTransform), typeof(VerticalLayoutGroup), typeof(ContentSizeFitter));
        content.transform.SetParent(viewport.transform, false);
        RectTransform contentRect = (RectTransform)content.transform;
        contentRect.anchorMin = new Vector2(0f, 1f);
        contentRect.anchorMax = new Vector2(1f, 1f);
        contentRect.pivot = new Vector2(0.5f, 1f);
        contentRect.anchoredPosition = Vector2.zero;
        contentRect.sizeDelta = Vector2.zero;

        VerticalLayoutGroup vertical = content.GetComponent<VerticalLayoutGroup>();
        vertical.spacing = rowSpacing;
        vertical.padding = new RectOffset(8, 8, 8, 8);
        vertical.childAlignment = TextAnchor.UpperCenter;
        vertical.childControlHeight = false;
        vertical.childControlWidth = true;
        vertical.childForceExpandHeight = false;
        vertical.childForceExpandWidth = true;

        ContentSizeFitter fitter = content.GetComponent<ContentSizeFitter>();
        fitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;
        fitter.horizontalFit = ContentSizeFitter.FitMode.Unconstrained;

        scrollRect.content = contentRect;
        rowsContainer = contentRect;

        TextMeshProUGUI status = CreateText(listArea, "StatusText", "", 38f, FontStyles.Bold, TextAlignmentOptions.Center);
        StretchFull((RectTransform)status.transform);
        status.color = new Color(1f, 1f, 1f, 0.9f);
        status.raycastTarget = false;
        status.gameObject.SetActive(false);
        statusText = status;
    }

    LeaderboardRowView CreateRow(int index)
    {
        LeaderboardRowView row = new LeaderboardRowView();

        GameObject rowGo = new GameObject("Row_" + (index + 1), typeof(RectTransform), typeof(Image), typeof(LayoutElement), typeof(HorizontalLayoutGroup));
        rowGo.transform.SetParent(rowsContainer, false);
        row.root = rowGo;
        row.background = rowGo.GetComponent<Image>();
        row.background.color = rowColorOdd;
        row.background.sprite = roundedSprite;
        row.background.type = Image.Type.Sliced;

        LayoutElement le = rowGo.GetComponent<LayoutElement>();
        le.preferredHeight = rowHeight;
        le.minHeight = rowHeight;
        le.flexibleWidth = 1f;

        HorizontalLayoutGroup horizontal = rowGo.GetComponent<HorizontalLayoutGroup>();
        horizontal.padding = new RectOffset(40, 40, 8, 8);
        horizontal.spacing = 18f;
        horizontal.childAlignment = TextAnchor.MiddleCenter;
        horizontal.childControlHeight = true;
        horizontal.childControlWidth = true;
        horizontal.childForceExpandHeight = true;
        horizontal.childForceExpandWidth = false;

        GameObject rankCell = new GameObject("RankCell", typeof(RectTransform), typeof(LayoutElement));
        rankCell.transform.SetParent(rowGo.transform, false);
        rankCell.GetComponent<LayoutElement>().flexibleWidth = 1f;

        GameObject medalGo = new GameObject("MedalBadge", typeof(RectTransform), typeof(Image));
        medalGo.transform.SetParent(rankCell.transform, false);
        RectTransform medalRect = (RectTransform)medalGo.transform;
        medalRect.anchorMin = new Vector2(0.5f, 0.5f);
        medalRect.anchorMax = new Vector2(0.5f, 0.5f);
        medalRect.pivot = new Vector2(0.5f, 0.5f);
        medalRect.sizeDelta = new Vector2(rowHeight * 0.7f, rowHeight * 0.7f);

        Image medal = medalGo.GetComponent<Image>();
        medal.sprite = circleSprite;
        medal.preserveAspect = true;
        medal.raycastTarget = false;
        row.medalBadge = medal;

        TextMeshProUGUI rankLabel = CreateText(rankCell.transform, "RankText", "1", 44f, FontStyles.Bold, TextAlignmentOptions.Center);
        StretchFull((RectTransform)rankLabel.transform);
        rankLabel.color = Color.white;
        rankLabel.raycastTarget = false;
        row.rankText = rankLabel;

        GameObject nameCell = new GameObject("NameCell", typeof(RectTransform), typeof(LayoutElement));
        nameCell.transform.SetParent(rowGo.transform, false);
        nameCell.GetComponent<LayoutElement>().flexibleWidth = 3f;

        TextMeshProUGUI nameLabel = CreateText(nameCell.transform, "NameText", "Player", 36f, FontStyles.Bold, TextAlignmentOptions.Left);
        StretchFull((RectTransform)nameLabel.transform);
        nameLabel.color = Color.white;
        nameLabel.enableAutoSizing = false;
        nameLabel.overflowMode = TextOverflowModes.Ellipsis;
        nameLabel.raycastTarget = false;
        row.nameText = nameLabel;

        GameObject scoreCell = new GameObject("ScoreCell", typeof(RectTransform), typeof(LayoutElement));
        scoreCell.transform.SetParent(rowGo.transform, false);
        scoreCell.GetComponent<LayoutElement>().flexibleWidth = 1.4f;

        TextMeshProUGUI scoreLabel = CreateText(scoreCell.transform, "ScoreText", "0", 40f, FontStyles.Bold, TextAlignmentOptions.Right);
        StretchFull((RectTransform)scoreLabel.transform);
        scoreLabel.color = scoreColor;
        scoreLabel.enableAutoSizing = false;
        scoreLabel.raycastTarget = false;
        row.scoreText = scoreLabel;

        return row;
    }

    void BuildYouFooter(RectTransform parent)
    {
        RectTransform footer = CreateChildRect(parent, "YouFooter",
            new Vector2(0f, 0f), new Vector2(1f, 0f), new Vector2(0.5f, 0f),
            new Vector2(20f, 30f), new Vector2(-20f, 200f));

        Image bg = footer.gameObject.AddComponent<Image>();
        bg.color = new Color(0.05f, 0.10f, 0.36f, 0.96f);
        bg.sprite = roundedSprite;
        bg.type = Image.Type.Sliced;
        youFooterBackground = bg;

        HorizontalLayoutGroup horizontal = footer.gameObject.AddComponent<HorizontalLayoutGroup>();
        horizontal.padding = new RectOffset(40, 40, 12, 12);
        horizontal.spacing = 18f;
        horizontal.childAlignment = TextAnchor.MiddleCenter;
        horizontal.childControlHeight = true;
        horizontal.childControlWidth = true;
        horizontal.childForceExpandHeight = true;
        horizontal.childForceExpandWidth = false;

        GameObject rankCell = new GameObject("YouRankCell", typeof(RectTransform), typeof(LayoutElement));
        rankCell.transform.SetParent(footer, false);
        rankCell.GetComponent<LayoutElement>().flexibleWidth = 1f;
        TextMeshProUGUI rank = CreateText(rankCell.transform, "YouRank", "-", 48f, FontStyles.Bold, TextAlignmentOptions.Center);
        StretchFull((RectTransform)rank.transform);
        rank.color = youHighlight;
        rank.raycastTarget = false;
        youRankText = rank;

        GameObject nameCell = new GameObject("YouNameCell", typeof(RectTransform), typeof(LayoutElement));
        nameCell.transform.SetParent(footer, false);
        nameCell.GetComponent<LayoutElement>().flexibleWidth = 3f;
        TextMeshProUGUI nameLabel = CreateText(nameCell.transform, "YouName", "You", 40f, FontStyles.Bold, TextAlignmentOptions.Left);
        StretchFull((RectTransform)nameLabel.transform);
        nameLabel.color = youHighlight;
        nameLabel.enableAutoSizing = false;
        nameLabel.overflowMode = TextOverflowModes.Ellipsis;
        nameLabel.raycastTarget = false;
        youNameText = nameLabel;

        GameObject scoreCell = new GameObject("YouScoreCell", typeof(RectTransform), typeof(LayoutElement));
        scoreCell.transform.SetParent(footer, false);
        scoreCell.GetComponent<LayoutElement>().flexibleWidth = 1.4f;
        TextMeshProUGUI scoreLabel = CreateText(scoreCell.transform, "YouScore", "-", 44f, FontStyles.Bold, TextAlignmentOptions.Right);
        StretchFull((RectTransform)scoreLabel.transform);
        scoreLabel.color = scoreColor;
        scoreLabel.enableAutoSizing = false;
        scoreLabel.raycastTarget = false;
        youScoreText = scoreLabel;

        BuildEditNameButton(parent);
    }

    void BuildEditNameButton(RectTransform parent)
    {
        GameObject btnGo = new GameObject("EditNameButton", typeof(RectTransform), typeof(Image), typeof(Button));
        btnGo.transform.SetParent(parent, false);
        RectTransform rect = (RectTransform)btnGo.transform;
        rect.anchorMin = new Vector2(0f, 0f);
        rect.anchorMax = new Vector2(0f, 0f);
        rect.pivot = new Vector2(0f, 0f);
        rect.anchoredPosition = new Vector2(40f, 220f);
        rect.sizeDelta = new Vector2(260f, 80f);

        Image img = btnGo.GetComponent<Image>();
        img.sprite = roundedSprite;
        img.type = Image.Type.Sliced;
        img.color = new Color(1f, 1f, 1f, 0.18f);

        TextMeshProUGUI label = CreateText(btnGo.transform, "Label", "Rename", 36f, FontStyles.Bold, TextAlignmentOptions.Center);
        StretchFull((RectTransform)label.transform);
        label.color = Color.white;

        Button btn = btnGo.GetComponent<Button>();
        btn.onClick.AddListener(OnEditNameClicked);
    }

    void OnEditNameClicked()
    {
        if (PlayerNameInputUI.instance != null)
        {
            PlayerNameInputUI.instance.ShowEditDialog(newName =>
            {
                ForceReloadFromFirebase();
            });
        }
    }

    Color MedalColor(int rank)
    {
        if (rank == 1) return medalGold;
        if (rank == 2) return medalSilver;
        return medalBronze;
    }

    static string TrimName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "Player";
        }
        string clean = name.Trim();
        const int max = 14;
        if (clean.Length <= max)
        {
            return clean;
        }
        return clean.Substring(0, max) + "…";
    }

    static string FormatScore(int score)
    {
        return score.ToString("N0", System.Globalization.CultureInfo.InvariantCulture);
    }

    static void ClearChildren(Transform parent)
    {
        for (int i = parent.childCount - 1; i >= 0; i--)
        {
            Transform child = parent.GetChild(i);
            if (Application.isPlaying)
            {
                Destroy(child.gameObject);
            }
            else
            {
                DestroyImmediate(child.gameObject);
            }
        }
    }

    static RectTransform CreateChildRect(RectTransform parent, string name, Vector2 anchorMin, Vector2 anchorMax, Vector2 pivot, Vector2 offsetMin, Vector2 offsetMax)
    {
        GameObject go = new GameObject(name, typeof(RectTransform));
        go.transform.SetParent(parent, false);
        RectTransform rect = (RectTransform)go.transform;
        rect.anchorMin = anchorMin;
        rect.anchorMax = anchorMax;
        rect.pivot = pivot;
        rect.offsetMin = offsetMin;
        rect.offsetMax = offsetMax;
        return rect;
    }

    static void StretchFull(RectTransform rect)
    {
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
    }

    static TextMeshProUGUI CreateText(Transform parent, string objectName, string content, float fontSize, FontStyles style, TextAlignmentOptions align)
    {
        GameObject go = new GameObject(objectName, typeof(RectTransform), typeof(TextMeshProUGUI));
        go.transform.SetParent(parent, false);
        TextMeshProUGUI text = go.GetComponent<TextMeshProUGUI>();
        text.text = content;
        text.fontSize = fontSize;
        text.fontStyle = style;
        text.alignment = align;
        text.color = Color.white;
        text.raycastTarget = false;
        return text;
    }

    static Texture2D BuildGradientTexture(int width, int height, Color top, Color bottom)
    {
        Texture2D tex = new Texture2D(width, height, TextureFormat.RGBA32, false);
        tex.wrapMode = TextureWrapMode.Clamp;
        tex.filterMode = FilterMode.Bilinear;

        for (int y = 0; y < height; y++)
        {
            float t = (float)y / Mathf.Max(1, height - 1);
            Color c = Color.Lerp(bottom, top, t);
            for (int x = 0; x < width; x++)
            {
                tex.SetPixel(x, y, c);
            }
        }
        tex.Apply(false, true);
        return tex;
    }

    static Sprite BuildCircleSprite(int size)
    {
        Texture2D tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
        tex.wrapMode = TextureWrapMode.Clamp;
        tex.filterMode = FilterMode.Bilinear;
        Color clear = new Color(0f, 0f, 0f, 0f);
        float radius = size * 0.5f;
        Vector2 center = new Vector2(radius, radius);
        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                float distance = Vector2.Distance(new Vector2(x + 0.5f, y + 0.5f), center);
                float alpha = Mathf.Clamp01(radius - distance);
                tex.SetPixel(x, y, alpha > 0f ? new Color(1f, 1f, 1f, alpha) : clear);
            }
        }
        tex.Apply(false, true);
        return Sprite.Create(tex, new Rect(0f, 0f, size, size), new Vector2(0.5f, 0.5f));
    }

    static Sprite BuildRoundedSprite(int size, int corner)
    {
        Texture2D tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
        tex.wrapMode = TextureWrapMode.Clamp;
        tex.filterMode = FilterMode.Bilinear;
        Color fill = Color.white;
        Color clear = new Color(0f, 0f, 0f, 0f);

        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                bool inside = true;
                int cornerSize = Mathf.Clamp(corner, 1, size / 2);

                if (x < cornerSize && y < cornerSize)
                {
                    float dx = cornerSize - x;
                    float dy = cornerSize - y;
                    inside = Mathf.Sqrt(dx * dx + dy * dy) <= cornerSize;
                }
                else if (x >= size - cornerSize && y < cornerSize)
                {
                    float dx = x - (size - cornerSize - 1);
                    float dy = cornerSize - y;
                    inside = Mathf.Sqrt(dx * dx + dy * dy) <= cornerSize;
                }
                else if (x < cornerSize && y >= size - cornerSize)
                {
                    float dx = cornerSize - x;
                    float dy = y - (size - cornerSize - 1);
                    inside = Mathf.Sqrt(dx * dx + dy * dy) <= cornerSize;
                }
                else if (x >= size - cornerSize && y >= size - cornerSize)
                {
                    float dx = x - (size - cornerSize - 1);
                    float dy = y - (size - cornerSize - 1);
                    inside = Mathf.Sqrt(dx * dx + dy * dy) <= cornerSize;
                }

                tex.SetPixel(x, y, inside ? fill : clear);
            }
        }
        tex.Apply(false, true);
        Sprite sprite = Sprite.Create(tex, new Rect(0f, 0f, size, size), new Vector2(0.5f, 0.5f), 100f, 0, SpriteMeshType.FullRect, new Vector4(corner, corner, corner, corner));
        return sprite;
    }
}
